-- WiWang Hotel by Floky
-- Do not edit this file unless you know what you're doing!
-- Do not edit this file unless you know what you're doing!
-- Do not edit this file unless you know what you're doing!
-- Do not edit this file unless you know what you're doing!
local zones = {}
local ipls = {
    ['floky_wiwang_hotel_01_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 42.382652),
        sets = 'wiwang01',
    },
    ['floky_wiwang_hotel_02_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 46.182652),
        sets = 'wiwang02',
    },
    ['floky_wiwang_hotel_03_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 49.982651),
        sets = 'wiwang03',
    },
    ['floky_wiwang_hotel_04_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 53.782650),
        sets = 'wiwang04',
    },
    ['floky_wiwang_hotel_05_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 57.582649),
        sets = 'wiwang05',
    },
    ['floky_wiwang_hotel_06_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 61.382648),
        sets = 'wiwang06',
    },
    ['floky_wiwang_hotel_07_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 65.182648),
        sets = 'wiwang07',
    },
    ['floky_wiwang_hotel_08_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 68.982651),
        sets = 'wiwang08',
    },
    ['floky_wiwang_hotel_09_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 72.782654),
        sets = 'wiwang09',
    },
    ['floky_wiwang_hotel_10_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 76.582657),
        sets = 'wiwang10',
    },
    ['floky_wiwang_hotel_11_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 80.382660),
        sets = 'wiwang11',
    },
    ['floky_wiwang_hotel_12_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 84.182663),
        sets = 'wiwang12',
    },
    ['floky_wiwang_hotel_13_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 87.982666),
        sets = 'wiwang13',
    },
    ['floky_wiwang_hotel_14_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 91.782669),
        sets = 'wiwang14',
    },
    ['floky_wiwang_hotel_15_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 95.582672),
        sets = 'wiwang15',
    },
    ['floky_wiwang_hotel_16_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 99.382675),
        sets = 'wiwang16',
    },
    ['floky_wiwang_hotel_17_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 103.182678),
        sets = 'wiwang17',
    },
    ['floky_wiwang_hotel_18_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 106.982681),
        sets = 'wiwang18',
    },
    ['floky_wiwang_hotel_19_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 110.782684),
        sets = 'wiwang19',
    },
    ['floky_wiwang_hotel_20_milo_'] = {
        coords = vector3(-823.606079, -708.511169, 114.582687),
        sets = 'wiwang20',
    },
}

local Unload = function()
    for ipl, _ in pairs(ipls) do
        RemoveIpl(ipl)
    end
    return true
end

function onEnter(self)
    if Unload() then
        Wait(200)
        RequestIpl(self.floor)
    end
end

function onExit(self)
    Unload()
end

for floor, data in pairs(ipls) do
    zones[floor] = lib.zones.box({
        coords = vec3(data.coords.x - 4.0, data.coords.y + 2.0, data.coords.z - 0.2),
        size = vec3(34, 50, 3.0),
        rotation = 0,
        debug = false,
        floor = floor,
        onEnter = onEnter,
        onExit = onExit
    })

    local coords = data.coords
    local interiorID = GetInteriorAtCoords(coords.x, coords.y, coords.z)
    if IsValidInterior(interiorID) then
        ActivateInteriorEntitySet(interiorID, data.sets)
        RefreshInterior(interiorID)
    end
end

Unload()
